=== nurshatsnr/testUnit/schemas/docusign_envelopes_create_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "http://example.com/example.json",
  "properties": {
    "program_identifier": {
      "enum": [
        "california_first",
        "renew_pace_florida"
      ]
    },
    "document_set_name": {
      "enum": [
        "completion_documents",
        "financing_documents"
      ]
    },
    "documents": {
      "items": {
        "properties": {
          "name": { "type": "string" },
          "data": { "type": "string" }
        },
        "type": "object",
        "required": [ "name", "data" ]
      },
      "type": "array",
      "minItems": 1
    },
    "recipients": {
      "items": {
        "properties": {
          "client_user_id": { "type": "string" },
          "email": { "type": "string", "format": "email" },
          "id_check": { "type": "boolean" },
          "identifier": { "type": "string" },
          "name": { "type": "string" },
          "recipient_type": { "type": "string" },
          "routing_order": { "type": "string" }
        },
        "type": "object",
        "required": [ "name", "email", "identifier" ]
      },
      "type": "array",
      "minItems": 1
    }
  },
  "required": ["program_identifier", "document_set_name", "documents", "recipients"],
  "type": "object"
}

=== nurshatsnr/testUnit/src/doc/raml/entities/examples/requests/docusign_envelopes_create_example.json
{
  "program_identifier": "california_first",
  "document_set_name": "financing_documents",
  "recipients": [
    {
      "name": "Person Guy",
      "email": "person@email.com",
      "identifier": "123-abc",
      "id_check": true,
      "recipient_type": "owner",
      "routing_order": "1",
      "client_user_id": "123-abc"
    },
    {
      "name": "A Person",
      "email": "email@person.com",
      "identifier": "890-xyz",
      "id_check": true,
      "recipient_type": "contractor",
      "routing_order": "1",
      "client_user_id": "890-xyz"
    }
  ],
  "documents": [
    {
      "name": "horses.docx",
      "data": "Base64 encoded data"
    },
    {
      "name": "ponies.docx",
      "data": "Base64 encoded data"
    }
  ]
}
